server:
  port: 8081
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://${USER_DB_HOST:localhost}:${USER_DB_PORT:5432}/cartzilla_user_db
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:dev-secret-key-change-me-please-32bytes!!}
  access-ttl-ms: 900000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
