server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native            # đọc config từ classpath/filesystem (dev đơn giản)
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
